name: Continuos Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build . -t eddyanalytics/eddy-python-flink-bridge:latest
      - name: Push Docker image
        run: |
          echo '${{ secrets.CI_REGISTRY_TOKEN }}' | docker login --username eddyanalytics --password-stdin
          docker push eddyanalytics/eddy-python-flink-bridge:latest
      - name: Check Tag
        id: check_tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=match::true
          fi
      - name: Release Version
        if: steps.check_tag.outputs.match == 'true'
        run: |
          docker tag eddyanalytics/eddy-python-flink-bridge:latest eddyanalytics/eddy-python-flink-bridge:${GITHUB_REF##*/}
          docker push eddyanalytics/eddy-python-flink-bridge:${GITHUB_REF##*/}
